# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  web-deploy:
    environment:
      name: github-pages
      url: https://reactjobportal.netlify.app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: "./dist"
      - name: 📂 Sync files test
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftp.codeinnepal.com.np
          username: nhhdpersonal@codeinnepal.com.np
          password: nhhd@2080
          port: 21
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
# on:
#   push:
#     branches:
#       - master
# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v2

#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: run npm install
#         run: npm install --legacy-peer-deps

#       - name: build
#         run: npm run build

#       - name: copy file from build to root
#         run: cp -r dist/* .

#       - name: 📂 Sync files test
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.0
#         with:
#           server: ftp.codeinnepal.com.np
#           username: hmsserver@hmsserver.codeinnepal.com.np
#           password: hms@2080
